### ISSUE TITLE
GO Term Chart Service

### ISSUE THREAD

**Issue by erasche** [ebi-uniprot/QuickGoFE#98]
Hi EBI, 

We would very much like to run a local copy of this service (and not abuse your's). I'm seeing urls going to `/services/chart` and `/services/chartfull` in the [template](https://github.com/ebi-uniprot/QuickGoFE/blob/master/app/charts/ontologyGraphModal.html) and associated controller.

However, I am not seeing these services represented in the QuickGoBE project. Is the ontology graph service code somewhere else accessible?

(Also wanted to say, amazing work on the new QuickGO, it looks great and functions perfectly. This project even seems to be a good resource for how to do some of the more complex things with angular.)

**Comment by rantunesboreas** [comment]
Hi Eric,


The code that you see in QuickGOBE is an ongoing major redesign of the current Beta version. We have opted to redesign the backend so that we can make it more scalable and to obtain even faster response times. The current code base is still under heavy development, and features are being added to it on a daily basis.


The ancestor chart, that you mentioned, is something we will starting adding next month. I apologize for this. We will try and anticipate its release if we can.


With the redesign we have also changed the naming of the REST endpoints to something one would expect from a REST service. We have started making changes to the QuickGOFE code base to mirror these URL changes, you can see the latest changes on the alpha branch.

Let us know if you have any further questions.

Regards,
     The QuickGO team
________________________________

**Comment by erasche** [comment]
Hey @rantunesboreas,

Just wanted to follow up and see if the ancestor chart was available yet. :) No pressure, we're just excited at the possibility of deploying that service locally.

**Comment by rantunesboreas** [comment]
Hi Eric,


Sorry for the late reply. We are busy trying to finalize our latest major release. This release should see our beta backend almost completely replaced with the version we have on github.


As for the ancestor chart we have released it. It is not yet to our liking, but you can find the endpoint that hosts it in:

https://github.com/ebi-uniprot/QuickGOBE/blob/master/ontology-rest/src/main/java/uk/ac/ebi/quickgo/ontology/controller/OBOController.java


under the getChart() method.


You can access a live test version on:


http://wwwdev.ebi.ac.uk/QuickGO/services/ontology/go/terms/GO:0006600/chart


However this version is used by us for development, so it can go down without warning.


We should release our new beta version by the end of next month, if everything goes to plan.


Regards,

     Ricardo


________________________________

**Comment by erasche** [comment]
Hey @rantunesboreas 

Awesome, thank you! This is really great to have.

Regards,
Eric
